#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# Rename the host
HOSTNAME=nginx
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# Enable locale zh_CN.UTF-8
/usr/share/locales/install-language-pack zh_CN.UTF-8
echo 'LANG=zh_CN.UTF-8' > /etc/default/locale
echo 'LC_ALL=zh_CN.UTF-8' >> /etc/default/locale

# Use mirrors.163.com as the default apt repository
rm -f /etc/apt/sources.list.d/*.list
apt-get update

# Install passenger and nginx
install libcurl4-openssl-dev
/usr/bin/env gem install passenger --no-ri --no-rdoc
/usr/bin/env ruby -S passenger-install-nginx-module --auto --auto-download --prefix=/usr/local/nginx
